/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as IndexImport } from './routes/index'
import { Route as AccountsRemoveRouteImport } from './routes/accounts/remove/route'
import { Route as AccountManagementEpicGamesSettingsRouteImport } from './routes/account-management/epic-games-settings/route'
import { Route as AccountsAddTypeImport } from './routes/accounts/add/$type'

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountsRemoveRouteRoute = AccountsRemoveRouteImport.update({
  path: '/accounts/remove',
  getParentRoute: () => rootRoute,
} as any)

const AccountManagementEpicGamesSettingsRouteRoute =
  AccountManagementEpicGamesSettingsRouteImport.update({
    path: '/account-management/epic-games-settings',
    getParentRoute: () => rootRoute,
  } as any)

const AccountsAddTypeRoute = AccountsAddTypeImport.update({
  path: '/accounts/add/$type',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/epic-games-settings': {
      preLoaderRoute: typeof AccountManagementEpicGamesSettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/accounts/remove': {
      preLoaderRoute: typeof AccountsRemoveRouteImport
      parentRoute: typeof rootRoute
    }
    '/accounts/add/$type': {
      preLoaderRoute: typeof AccountsAddTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRouteRoute,
  AccountManagementEpicGamesSettingsRouteRoute,
  AccountsRemoveRouteRoute,
  AccountsAddTypeRoute,
])

/* prettier-ignore-end */
